# This file controls the settings for your Quarto template 

# website settings
website:
  title: "Misja Mikkers"                                # Your name
  description: "Misja Mikkers is professor of Health Systems Engineering at the University of Twente"   # A brief slogan (optional)
  image: img/misja.png
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/misja.png
    
    # your sub-pages
    left:
      - text: "About"
        href: about/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
    
    # social media handles
    right:
      - icon: folder-symlink
        href: https://people.utwente.nl/m.c.mikkers
      - icon: mastadon
        href: https://twitter.com/MarvinSchmittML
      - icon: linkedin
        href: https://www.linkedin.com/in/misja-m-413b924/
      - icon: envelope
        aria-label: email
        href: "mailto:m.c.mikkers@utwente.nl"  
  
  


project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true